-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.material_type
(
    id serial NOT NULL,
    material_type character varying(155) COLLATE pg_catalog."default",
    broke numeric(2, 4),
    CONSTRAINT material_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partner_products
(
    id serial NOT NULL,
    product character varying(155) COLLATE pg_catalog."default",
    partner_name character varying(155) COLLATE pg_catalog."default",
    value_product bigint,
    data date,
    partner_id integer,
    product_id integer,
    materialtype_id integer,
    CONSTRAINT partner_products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partners
(
    id serial NOT NULL,
    partner_type character varying(155) COLLATE pg_catalog."default",
    partner_name character varying(155) COLLATE pg_catalog."default",
    director character varying(155) COLLATE pg_catalog."default",
    mail character varying(155) COLLATE pg_catalog."default",
    tel character varying COLLATE pg_catalog."default",
    adress character varying(155) COLLATE pg_catalog."default",
    inn bigint,
    rate bigint,
    CONSTRAINT partners_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    id serial NOT NULL,
    product_type character varying(155) COLLATE pg_catalog."default",
    cf numeric(10, 2),
    CONSTRAINT product_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    "Id" serial NOT NULL,
    product_type character varying(155) COLLATE pg_catalog."default",
    product_name character varying(155) COLLATE pg_catalog."default",
    article bigint,
    min_count numeric(10, 2),
    product_type_id integer,
    CONSTRAINT products_pkey PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public.partner_products
    ADD CONSTRAINT fk_materialtype FOREIGN KEY (materialtype_id)
    REFERENCES public.material_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partner_products
    ADD CONSTRAINT fk_partner FOREIGN KEY (partner_id)
    REFERENCES public.partners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partner_products
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id)
    REFERENCES public.products ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_product FOREIGN KEY (product_type_id)
    REFERENCES public.product_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;